apiVersion: v1
kind: Service
metadata:
  name: whisper-medium-service
spec:
  selector:
    app: whisper-medium-api
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: ClusterIP
